version: "3.9"

networks:
  devnet:
    name: devnet
    external: true
  dora:
    name: dora
    driver: bridge

services:
  dora:
    image: pk910/dora-the-explorer:latest
    container_name: dora
    restart: unless-stopped
    ports:
      - "3070:3070"
    volumes:
      - ./config:/config:ro # read-only config
    networks:
      - dora
      - devnet
    command: -config=/config/explorer-config.yaml
