{
 "title": "Rewards & Penalties",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "1h",
 "templating": {
  "list": [
   {
    "name": "epochs_range",
    "label": "Epochs range",
    "query": {
     "query": "query_result(sum_over_time((changes(sum(ethereum_validators_monitoring_epoch_number)[25s:]) > 0)[$__range:]))"
    }
   },
   {
    "name": "module_var",
    "label": "Module",
    "query": {
     "query": "label_values(ethereum_validators_monitoring_validators,nos_module_id)"
    }
   },
   {
    "name": "nos_name_array_var",
    "label": "Node Operator",
    "query": {
     "query": "query_result(ethereum_validators_monitoring_user_validators{nos_module_id=~'${module_var}'})"
    }
   }
  ]
 },
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data actuality",
   "type": "stat",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)"
    }
   ]
  },
  {
   "title": "Data actuality x Epoch",
   "type": "timeseries",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)",
     "legendFormat": "Data actuality"
    },
    {
     "expr": "ethereum_validators_monitoring_epoch_number",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Calculation error",
   "type": "stat",
   "description": "Related to 'inactivity leaks' or 'slashing case' or math accuracy",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time((sum(ethereum_validators_monitoring_operator_calculated_balance_calculation_error{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / sum_over_time((sum(ethereum_validators_monitoring_operator_real_balance_delta{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])) * 100"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Last processed for a specified time period",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_epoch_number)"
    }
   ]
  },
  {
   "title": "⛓️ Average chain validator stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Attestation reward",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_reward{duty=\"attestation\"} and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Proposal reward",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_reward{duty=\"proposal\"} / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Sync reward",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_reward{duty=\"sync\"} and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Attestation penalty",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_penalty{duty=\"attestation\"} and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Sync penalty",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_penalty{duty=\"sync\"} and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Attestation missed reward",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_missed_reward{duty=\"attestation\"} and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Proposal missed reward",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 8, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "ETH" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_missed_reward{duty=\"proposal\"} / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    },
    {
     "title": "Sync missed reward",
     "type": "timeseries",
     "gridPos": { "h": 4, "w": 8, "x": 16, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "GWei" } },
     "targets": [
      {
       "expr": "ethereum_validators_monitoring_avg_chain_missed_reward{duty=\"sync\"} and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "avg"
      }
     ]
    }
   ]
  },
  { "title": "🏦 Total", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "Life line",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum by () (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "Rewards"
    },
    {
     "expr": "sum by () (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) / 10^9 AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "Penalties"
    },
    {
     "expr": "sum by () (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) / 10^9 AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "Missed rewards"
    },
    {
     "expr": "sum by () (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "Rewards (line)"
    },
    {
     "expr": "sum by () (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "Penalties (line)"
    },
    {
     "expr": "sum by () (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
     "legendFormat": "Missed rewards (line)"
    }
   ]
  },
  {
   "title": "Total reward effectiveness progress",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "((sum by () (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0)) / (((sum by () (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0)) + ((sum by () (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0)) + (sum by () (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0)) * 100",
     "legendFormat": "Percent"
    }
   ]
  },
  {
   "title": "Total reward eff. (${epochs_range} epochs range)",
   "type": "bargauge",
   "gridPos": { "h": 3, "w": 8, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(sum_over_time((sum by () (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])) / ((sum_over_time((sum by () (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])) + (sum_over_time((sum by () (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])) + sum_over_time((sum by () (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:])) * 100"
    }
   ]
  },
  {
   "title": "Total summary (${epochs_range} epochs range)",
   "type": "table",
   "gridPos": { "h": 13, "w": 16, "x": 8, "y": 19 },
   "targets": [
    {
     "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
     "legendFormat": "{{nos_name}}"
    },
    {
     "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
     "legendFormat": "{{nos_name}}"
    },
    {
     "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
     "legendFormat": "{{nos_name}}"
    },
    {
     "expr": "(sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_calculated_balance_calculation_error{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9)",
     "legendFormat": "{{nos_name}}"
    },
    {
     "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_withdrawals_sum{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
     "legendFormat": "{{nos_name}}"
    }
   ]
  },
  {
   "title": "Total rewards",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9"
    }
   ]
  },
  {
   "title": "Total earned",
   "type": "stat",
   "description": "total_rewards - total_penalties",
   "gridPos": { "h": 6, "w": 5, "x": 3, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ETH ⛏️" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_operator_calculated_balance_delta{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
     "legendFormat": "Total sum"
    }
   ]
  },
  {
   "title": "Total penalties",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 25 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9"
    }
   ]
  },
  {
   "title": "Total missed rewards",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9"
    }
   ]
  },
  {
   "title": "Total withdrawn",
   "type": "stat",
   "gridPos": { "h": 2, "w": 8, "x": 0, "y": 30 },
   "fieldConfig": { "defaults": { "unit": "ETH" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum_over_time((sum by () (ethereum_validators_monitoring_operator_withdrawals_sum{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9"
    }
   ]
  },
  {
   "title": "🟩 Rewards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Rewards summary (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 57 },
     "targets": [
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_reward{duty=\"attestation\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_reward{duty=\"proposal\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_reward{duty=\"sync\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Per operator",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 13, "x": 11, "y": 57 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_operator_reward{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🟥 Penalties",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "Penalties summary (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 58 },
     "targets": [
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_penalty{duty=\"attestation\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_penalty{duty=\"sync\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Per operator",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 13, "x": 11, "y": 58 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_operator_penalty{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🟪 Missed rewards",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Missed rewards summary (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 59 },
     "targets": [
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_missed_reward{duty=\"attestation\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_missed_reward{duty=\"proposal\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_missed_reward{duty=\"sync\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Per operator",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 13, "x": 11, "y": 59 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_operator_missed_reward{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "🟨 Withdrawals",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Withdrawals summary (${epochs_range} epochs range)",
     "type": "table",
     "gridPos": { "h": 13, "w": 11, "x": 0, "y": 60 },
     "targets": [
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_withdrawals_sum{type=\"partial\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_withdrawals_sum{type=\"full\", nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      },
      {
       "expr": "sum_over_time((sum by (nos_name) (ethereum_validators_monitoring_operator_withdrawals_sum{nos_name=~'${nos_name_array_var}'}) AND ON() changes(ethereum_validators_monitoring_epoch_number[25s]) > 0)[$__range:]) / 10^9",
       "legendFormat": "{{nos_name}}"
      }
     ]
    },
    {
     "title": "Per operator",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 13, "x": 11, "y": 60 },
     "targets": [
      {
       "expr": "sum by (nos_name) (ethereum_validators_monitoring_operator_withdrawals_sum{nos_name=~'${nos_name_array_var}'}) / 10^9 and on() changes(ethereum_validators_monitoring_epoch_number[$__rate_interval]) > 0",
       "legendFormat": "{{nos_name}}"
      }
     ]
    }
   ]
  }
 ]
}