{
 "title": "Validators - All",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5m",
 "panels": [
  { "title": "App", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Data actuality",
   "type": "stat",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)"
    }
   ]
  },
  {
   "title": "Data actuality x Epoch",
   "type": "timeseries",
   "description": "Difference between `Now` and timestamp of last slot of processed epoch ",
   "gridPos": { "h": 4, "w": 15, "x": 5, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_data_actuality)",
     "legendFormat": "Data actuality"
    },
    {
     "expr": "ethereum_validators_monitoring_epoch_number",
     "legendFormat": "Epoch"
    }
   ]
  },
  {
   "title": "Epoch",
   "type": "stat",
   "description": "Last processed for a specified time period",
   "gridPos": { "h": 2, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_epoch_number)"
    }
   ]
  },
  { "title": "🏠 General", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Ongoing Lido Validators",
   "type": "stat",
   "gridPos": { "h": 3, "w": 5, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (ethereum_validators_monitoring_validators{owner=\"user\",status=\"ongoing\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Pending Lido Validators",
   "type": "stat",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 5, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"pending\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawal pending Lido",
   "type": "stat",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 3, "w": 5, "x": 10, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_pending\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Full withdrawn Lido",
   "type": "stat",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 3, "w": 5, "x": 15, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_done\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Slashed Lido Validators",
   "type": "stat",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"slashed\"})",
     "legendFormat": "{{owner}}"
    }
   ]
  },
  {
   "title": "Ongoing Validators",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 5, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"ongoing\"})",
     "legendFormat": "Lido"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"ongoing\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Pending Validators",
   "type": "piechart",
   "description": "Alias for `pending_queued` and `pending_initialized` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 5, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"pending\"})",
     "legendFormat": "Lido"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"pending\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Full withdrawal pending",
   "type": "piechart",
   "description": "Alias for `active_exiting`, `exited_unslashed`, `exited_slashed` and `withdrawal_possible` statuses",
   "gridPos": { "h": 7, "w": 5, "x": 10, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_pending\"})",
     "legendFormat": "Lido"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"withdrawal_pending\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Full withdrawn",
   "type": "piechart",
   "description": "Alias for `withdrawal_done`, and `withdrawal_possible` statuses. `withdrawal_possible` is considered fully withdrawn when the validator balance is `0`.",
   "gridPos": { "h": 7, "w": 5, "x": 15, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"withdrawal_done\"})",
     "legendFormat": "Lido"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"withdrawal_done\"})",
     "legendFormat": "Other"
    }
   ]
  },
  {
   "title": "Slashed Validators",
   "type": "piechart",
   "description": "Alias for `active_slashed`, `exited_slashed` or any validator status with `slashed = true` in state",
   "gridPos": { "h": 7, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "locale" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"user\",status=\"slashed\"})",
     "legendFormat": "Lido"
    },
    {
     "expr": "sum(ethereum_validators_monitoring_validators{owner=\"other\",status=\"slashed\"})",
     "legendFormat": "Other"
    }
   ]
  }
 ]
}