{{- if .Values.alertmanager.slack.secretData }}
{{- if gt (len .Values.alertmanager.slack.secretData) 0 }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-alertmanager-slack
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alertmanager
type: Opaque
stringData:
{{- range $key, $value := .Values.alertmanager.slack.secretData }}
  {{ $key }}: {{ $value | quote }}
{{- end }}
{{- end }}
{{- end }}
