apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-alertmanager
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alertmanager
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: alertmanager
  ports:
    - name: http
      port: {{ .Values.alertmanager.port }}
      targetPort: {{ .Values.alertmanager.port }}
      protocol: TCP
