apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-prometheus
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: prometheus
  ports:
    - name: http
      port: {{ .Values.prometheus.port }}
      targetPort: {{ .Values.prometheus.port }}
      protocol: TCP
