version: "3.9"

services:
  # Creates a genesis state for the beacon chain using a YAML configuration file and
  # a deterministic set of 64 validators.
  create-beacon-chain-genesis:
    platform: linux/amd64
    image: "gcr.io/prysmaticlabs/prysm/cmd/prysmctl:HEAD-ae3663"
    command:
      - testnet
      - generate-genesis
      - --fork=deneb
      - --num-validators=64
      - --genesis-time-delay=15
      - --output-ssz=/consensus/genesis.ssz
      - --chain-config-file=/consensus/config.yml
      - --geth-genesis-json-in=/execution/genesis.json
      - --geth-genesis-json-out=/execution/genesis.json
    volumes:
      - ../consensus:/consensus
      - ../execution:/execution
