version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true
  blockscout:
    name: blockscout-${DOCKER_NETWORK_NAME}
    external: true

services:
  user-ops-indexer:
    image: ghcr.io/blockscout/user-ops-indexer:${USER_OPS_INDEXER_DOCKER_TAG:-latest}
    
    platform: linux/amd64
    restart: always
    networks:
      - blockscout
      - devnet
    env_file:
      -  ../envs/common-user-ops-indexer.env
    environment:
      - USER_OPS_INDEXER__INDEXER__RPC_URL=${USER_OPS_INDEXER__INDEXER__RPC_URL:-ws://execution:8546/}
      - USER_OPS_INDEXER__DATABASE__CONNECT__URL=${USER_OPS_INDEXER__DATABASE__CONNECT__URL:-postgresql://blockscout:ceWb1MeLBEeOIfk65gU8EjF8@db:5432/blockscout}
      - USER_OPS_INDEXER__DATABASE__RUN_MIGRATIONS=true
