version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true
  blockscout:
    name: blockscout-${DOCKER_NETWORK_NAME}
    external: true

services:
  visualizer:
    image: ghcr.io/blockscout/visualizer:${VISUALIZER_DOCKER_TAG:-latest}
    
    platform: linux/amd64
    restart: always
    networks:
      - blockscout
    env_file:
      -  ../envs/common-visualizer.env
