{{- if and (not .Values.jwt.existingSecret) .Values.jwt.secret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "lido-cl-node.fullname" . }}-jwt
  labels:
    {{- include "lido-cl-node.labels" . | nindent 4 }}
type: Opaque
data:
  jwt.hex: {{ .Values.jwt.secret | b64enc | quote }}
{{- end }}
