apiVersion: v1
kind: Service
metadata:
  name: {{ include "lido-cl-node.fullname" . }}
  labels:
    {{- include "lido-cl-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.ports.http }}
      targetPort: http
      protocol: TCP
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "lido-cl-node.selectorLabels" . | nindent 4 }}
