version: '3.9'

networks:
  devnet:
    name: devnet
    external: true
  blockscout:
    name: devnet
    external: true

services:
  proxy:
    image: nginx
    container_name: proxy
    volumes:
      - "../proxy:/etc/nginx/templates"
    environment:
      BACK_PROXY_PASS: ${BACK_PROXY_PASS:-http://backend:4000}
      FRONT_PROXY_PASS: ${FRONT_PROXY_PASS:-http://frontend:3000}
    networks:
      - blockscout
      - devnet
    ports:
      - target: 80
        published: 3080
      - target: 8080
        published: 8080
      - target: 8081
        published: 8081
