version: '3.9'

networks:
  devnet:
    name: devnet
    external: true
  blockscout:
    name: devnet
    external: true

services:
  sig-provider:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    networks:
      - blockscout
    container_name: 'sig-provider'
