version: '3.9'

networks:
  devnet:
    name: devnet
    external: true
  blockscout:
    name: devnet
    external: true

services:
  frontend:
    image: ghcr.io/blockscout/frontend:${FRONTEND_DOCKER_TAG:-latest}
    pull_policy: always
    platform: linux/amd64
    restart: always
    container_name: 'frontend'
    networks:
      - blockscout
    env_file:
      -  ../envs/common-frontend.env
