version: '3.9'

networks:
  devnet:
    name: devnet
    external: true
  blockscout:
    name: devnet
    external: true

services:
  redis-db:
    image: 'redis:alpine'
    container_name: redis-db
    command: redis-server
    networks:
      - blockscout
    volumes:
      - redis-data:/data
