apiVersion: v1
kind: Service
metadata:
  name: {{ include "lido-validator-node.fullname" . }}
  labels:
    {{- include "lido-validator-node.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: keymanager
      port: {{ .Values.ports.keymanager }}
      targetPort: keymanager
      protocol: TCP
    - name: metrics
      port: {{ .Values.ports.metrics }}
      targetPort: metrics
      protocol: TCP
  selector:
    {{- include "lido-validator-node.selectorLabels" . | nindent 4 }}
