version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true
  blockscout:
    name: blockscout-${DOCKER_NETWORK_NAME}
    external: true

services:
  backend:
    image: blockscout/${DOCKER_REPO:-blockscout}:${DOCKER_TAG:-latest}
    
    restart: always
    stop_grace_period: 5m
    command: sh -c "bin/blockscout eval \"Elixir.Explorer.ReleaseTasks.create_and_migrate()\" && bin/blockscout start"
    env_file:
      -  ../envs/common-blockscout.env
    networks:
      - blockscout
      - devnet
    volumes:
      - logs-data:/app/logs/
