version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true
  blockscout:
    name: blockscout-${DOCKER_NETWORK_NAME}
    external: true

services:
  redis-db:
    image: 'redis:alpine'
    command: redis-server
    networks:
      - blockscout
    volumes:
      - redis-data:/data
