version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true
  blockscout:
    name: blockscout-${DOCKER_NETWORK_NAME}
    external: true

services:
  sig-provider:
    image: ghcr.io/blockscout/sig-provider:${SIG_PROVIDER_DOCKER_TAG:-latest}
    
    platform: linux/amd64
    restart: always
    networks:
      - blockscout
