apiVersion: v2
name: lido-vroom-onchain-mon
description: Lido VROOM Onchain Monitoring Helm chart
type: application
version: 1.0.0
appVersion: "0.0.1"
kubeVersion: '>=1.19.0-0'
dependencies:
  - name: "lido-app"
    version: "1.0.1"
    repository: "file://../lido-app"
