@@ -0,0 +1,156 @@
version: "3.9"

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true

services:
  lido-oracle-accounting1:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: accounting

  lido-oracle-ejector1:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: ejector

  lido-oracle-accounting2:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: accounting

  lido-oracle-ejector2:
    build: ./
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: ejector

  lido-oracle-accounting3:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_2}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_3}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: accounting

  lido-oracle-ejector3:
    build: ./
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_2}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_3}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: ejector
No newline at end of file
