---
version: '3.9'

networks:
  devnet:
    name: ${DOCKER_NETWORK_NAME}
    external: true

services:
  lido-oracle-accounting:
    # build: ./
    image: lidofinance/oracle:4.1.1
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5679:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: accounting

  lido-oracle-ejector:
    build: ./
    # image: lidofinance/oracle:4.1.1
    # platform: linux/amd64
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5680:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: ejector

  lido-oracle-csm:
    build: ./
    # image: lidofinance/oracle:4.1.1
    # platform: linux/amd64
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5681:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_1}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "CSM_MODULE_ADDRESS=${CSM_MODULE_ADDRESS}"
      - "CSM_ORACLE_MAX_CONCURRENCY=1"
      - "PINATA_JWT=${PINATA_JWT}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: csm

  lido-oracle-accounting-v5:
    build: ./
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5682:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: accounting

  lido-oracle-ejector-v5:
    build: ./
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5683:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: ejector

  lido-oracle-csm-v5:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5684:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_2}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "CSM_MODULE_ADDRESS=${CSM_MODULE_ADDRESS}"
      - "CSM_ORACLE_MAX_CONCURRENCY=1"
      - "PINATA_JWT=${PINATA_JWT}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: csm

  lido-oracle-accounting-v5.2:
    build: ./
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-accounting"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5685:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_2}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_3}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "ALLOW_REPORTING_IN_BUNKER_MODE=false"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: accounting

  lido-oracle-ejector-v5.2:
    build: ./
    restart: unless-stopped

    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "1"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_2}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_3}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: ejector

  lido-oracle-csm-v5.2:
    build: ./
    restart: unless-stopped
    networks:
      - devnet
    deploy:
      resources:
        limits:
          cpus: "2"
          memory: 4G
    labels:
      - "prometheus-job=lido-oracle-ejector"
      - "prometheus-endpoint=/"
      - "prometheus-port=9000"
    ports:
      - 5686:5678
    environment:
      - "PROMETHEUS_PORT=9000"
      - "EXECUTION_CLIENT_URI=${EXECUTION_CLIENT_URI}"
      - "CONSENSUS_CLIENT_URI=${CONSENSUS_CLIENT_URI_2}"
      - "KEYS_API_URI=http://keys_api:9030"
      - "MEMBER_PRIV_KEY=${MEMBER_PRIV_KEY_3}"
      - "LIDO_LOCATOR_ADDRESS=${LIDO_LOCATOR_ADDRESS}"
      - "CSM_MODULE_ADDRESS=${CSM_MODULE_ADDRESS}"
      - "CSM_ORACLE_MAX_CONCURRENCY=1"
      - "PINATA_JWT=${PINATA_JWT}"
      - "SUBMIT_DATA_DELAY_IN_SLOTS=1"
    command: csm
