participants:
  - el_type: besu
    el_image: ethpandaops/besu:pectra-devnet-5-interop-cb1357e
    cl_type: lighthouse
    cl_image: ethpandaops/lighthouse:unstable-7e0cdde
    count: 2g

network_params:
  network_id: "32382"
  electra_fork_epoch: 3
  min_validator_withdrawability_delay: 1
  shard_committee_period: 1
  eth1_follow_distance: 12
  seconds_per_slot: 12
  # seconds_per_eth1_block: 12
  # slots_per_epoch: 32
  preset: minimal #minimal
  # preset: mainnet #minimal

keymanager_enabled: true

additional_services:
  # - assertoor
  - dora
# assertoor_params:
#   image: "ethpandaops/assertoor:master"
#   run_stability_check: false
#   run_block_proposal_check: falseOracleReportLimits
#   tests:
#     - https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/validator-withdrawal-test.yaml
#     - https://raw.githubusercontent.com/ethpandaops/assertoor-test/master/assertoor-tests/validator-exit-test.yaml

port_publisher:
  el:
    enabled: true
    public_port_start: 32000
  cl:
    enabled: true
    public_port_start: 33000

  # dora
  additional_services:
    enabled: true
    public_port_start: 34000
