participants:
participants:
  - el_type: geth
    el_image: ethpandaops/geth:prague-devnet-5-a193537
    cl_type: teku
    cl_image: ethpandaops/teku:master-cc94afc
    cl_extra_env_vars: { "JAVA_TOOL_OPTIONS": "-XX:UseSVE=0" } # for apple M4
    count: 1

network_params:
  network_id: "32382"
  electra_fork_epoch: 3
  min_validator_withdrawability_delay: 1
  shard_committee_period: 1
  eth1_follow_distance: 12
  seconds_per_slot: 12
  # seconds_per_eth1_block: 12
  # slots_per_epoch: 32
  # preset: mainnet #minimal
  preset: mainnet #minimal

keymanager_enabled: true

additional_services:
  - assertoor
  - dora
assertoor_params:
  image: "ethpandaops/assertoor:master-f0413d8"
  tests:
    - file: https://raw.githubusercontent.com/ethpandaops/assertoor/refs/heads/master/playbooks/pectra-dev/kurtosis/all.yaml

port_publisher:
  el:
    enabled: true
    public_port_start: 32000
  cl:
    enabled: true
    public_port_start: 33000

  # dora
  additional_services:
    enabled: true
    public_port_start: 34000
